version: "3.9"
services:
  sql:
    image: postgres:15.1-alpine
    container_name: ${DB_TEST_NAME}
    environment:
      POSTGRES_DB: ${DB_TEST_NAME}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_TEST_NAME}"]
      interval: 3s
      timeout: 9s
      retries: 3
    ports:
      - "${DB_PORT}:5432"
    networks:
      - test_network

  redis:
    image: redis:7.2-rc-alpine
    restart: always
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    environment:
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD}"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 1
    ports:
      - "${REDIS_PORT}:6379"
    expose:
      - "${REDIS_PORT}"
    networks:
      - test_network

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      DB_NAME: ${DB_TEST_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: 6379
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "8000:8000"
    entrypoint: sh -c "pytest; exit"
    networks:
      - test_network
    depends_on:
      sql:
        condition: service_healthy
      redis:
        condition: service_healthy

networks:
  test_network:
    name: test_network
